@extends('layout')
@section('title','Administração')
@section('content')<main id="main" class="admin-page"><a href="/mail">← Voltar às caixas</a><div class="page-heading"><div><div class="eyebrow">CONTROLES DO BRN MAIL</div><h1>Administração</h1></div><span class="status">Somente master</span></div>
<section class="panel"><h2>Integração e operação</h2><div class="info-grid"><div><strong>Transporte</strong><p>{{ config('brnmail.transport')==='local'?'Simulador local':'Resend' }}</p></div><div><strong>Envio externo</strong><p>{{ config('brnmail.external_enabled')?'Habilitado para lista autorizada':'Bloqueado' }}</p></div><div><strong>Credencial Resend</strong><p>{{ $hasProviderKey?'Configurada · não exibida':'Não configurada' }}</p></div><div><strong>Antivírus</strong><p>Indisponível mantém os anexos em quarentena.</p></div></div><p class="muted">Credenciais reais e destinatários de homologação serão configurados somente após liberação. Nenhum DNS foi alterado.</p><details><summary>Cofre de credenciais · somente após liberação</summary><form method="post" action="/admin/provider" autocomplete="off">@csrf<label>Nova chave de API Resend<input type="password" name="api_key" autocomplete="new-password" placeholder="Vazio preserva a chave existente"></label><label>Novo segredo de assinatura do webhook<input type="password" name="webhook_secret" autocomplete="new-password" placeholder="Vazio preserva o segredo existente"></label><label>Destinatários autorizados para teste, separados por vírgula<input name="test_recipients" placeholder="Vazio bloqueia todos os destinatários"></label><label>Confirme sua senha<input type="password" name="password" required autocomplete="current-password"></label><button>Salvar no cofre, sem ativar envios</button></form></details></section>
<div class="admin-grid"><section class="panel"><h2>Empresas</h2>@foreach($organizations as $o)<p>{{ $o->name }}</p>@endforeach<form method="post" action="/admin/organizations">@csrf<label>Nome da empresa<input name="name" required maxlength="100"></label><label>Confirme sua senha<input type="password" name="password" required autocomplete="current-password"></label><button>Criar empresa isolada</button></form></section>
<section class="panel"><h2>Produtos</h2>@foreach($products as $p)<p>{{ $p->name }}</p>@endforeach<form action="/admin/products" method="post">@csrf<label>Empresa<select name="organization_id">@foreach($organizations as $o)<option value="{{ $o->id }}">{{ $o->name }}</option>@endforeach</select></label><label>Nome do produto<input name="name" required maxlength="100"></label><button>Criar produto</button></form></section>
<section class="panel"><h2>Confirmar domínio no Resend</h2><p>Somente após liberação e configuração das credenciais. Consulta o estado do domínio, sem alterar DNS ou MX.</p><form method="post" action="/admin/domain-status">@csrf<label>Domínio cadastrado<select name="mail_domain_id">@foreach($domains as $d)<option value="{{ $d->id }}">{{ $d->domain }}</option>@endforeach</select></label><label>ID do domínio no Resend<input name="provider_id" required></label><label>Confirme sua senha<input name="password" type="password" required autocomplete="current-password"></label><button>Consultar estado no provedor</button></form></section>
<section class="panel"><h2>Domínios</h2>@foreach($domains as $d)<p><strong>{{ $d->domain }}</strong> · {{ $d->status==='verified'?'Verificado':($d->status==='local'?'Somente local':'Pendente') }}</p>@endforeach<form method="post" action="/admin/domains">@csrf<label>Produto<select name="product_id">@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></label><label>Domínio<input name="domain" required placeholder="exemplo.com"></label><button>Cadastrar como pendente</button></form></section>
<section class="panel"><h2>Caixas</h2>@foreach($boxes as $b)<p>{{ $b->name }} · {{ $b->address }} {{ $b->sensitive?'· Sensível':'' }}</p>@endforeach<form method="post" action="/admin/mailboxes">@csrf<label>Domínio<select name="mail_domain_id">@foreach($domains as $d)<option value="{{ $d->id }}">{{ $d->domain }}</option>@endforeach</select></label><label>Nome<input name="name" required></label><label>Endereço<input name="address" type="email" required></label><label class="check"><input name="sensitive" type="checkbox" value="1"> Correspondência sensível</label><button>Criar caixa</button></form></section>
<section class="panel"><h2>Convite individual</h2><p>Sem cadastro público e sem permissão automática de leitura. Para vincular uma conta já existente, use Permissões por caixa.</p><form method="post" action="/admin/invites">@csrf<label>Empresa<select name="organization_id">@foreach($organizations as $o)<option value="{{ $o->id }}">{{ $o->name }}</option>@endforeach</select></label><label>E-mail da pessoa<input type="email" name="email" required></label><button>Criar convite privado</button></form></section>
<section class="panel"><h2>Alias de recebimento</h2><p>Um endereço adicional no mesmo domínio, entregando na caixa escolhida. Não cria outra permissão de leitura.</p><form method="post" action="/admin/aliases">@csrf<label>Caixa de destino<select name="mailbox_id">@foreach($boxes as $b)<option value="{{ $b->id }}">{{ $b->address }}</option>@endforeach</select></label><label>Endereço do alias<input type="email" name="address" required></label><label>Confirme sua senha<input type="password" name="password" required autocomplete="current-password"></label><button>Cadastrar alias</button></form></section>
<section class="panel"><h2>Permissões por caixa</h2>
<p>Use a conta existente da pessoa para acessar uma ou mais caixas. Não é necessário criar outro login ou aceitar um convite.</p>
<form method="post" action="/admin/grants">@csrf
<label>Pessoa<select name="user_id">@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->name }} · {{ $u->email }}</option>@endforeach</select></label>
<fieldset><legend>Caixas que receberão estas permissões</legend>
@foreach($boxes as $b)<label class="check"><input type="checkbox" name="mailbox_ids[]" value="{{ $b->id }}"> {{ $b->address }}{{ $b->sensitive?' · Sensível':'' }}</label>@endforeach
</fieldset>
<label class="check"><input type="checkbox" name="add_membership" value="1"> Vincular esta conta às empresas das caixas selecionadas</label>
<p class="muted">Marque se a pessoa ainda não pertence a essas empresas. Sua senha e seu autenticador serão mantidos. A opção não reativa acessos revogados.</p>
<label class="check"><input type="checkbox" name="can_read" value="1"> Ler mensagens</label>
<label class="check"><input type="checkbox" name="can_send" value="1"> Redigir, responder e organizar</label>
<label class="check"><input type="checkbox" name="view_sensitive" value="1"> Acesso explícito às caixas sensíveis selecionadas</label>
<label>Confirme sua senha<input name="password" type="password" required autocomplete="current-password"></label>
<button class="primary">Aplicar às caixas selecionadas</button>
<p class="muted">As permissões acima substituem as atuais somente nas caixas selecionadas. Caixas não selecionadas permanecem como estão. Uma única confirmação de senha aplica o vínculo solicitado e as permissões.</p>
</form></section>
<section class="panel"><h2>Remover acesso à empresa</h2><form method="post" action="/admin/revoke">@csrf<label>Pessoa<select name="user_id">@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></label><label>Empresa<select name="organization_id">@foreach($organizations as $o)<option value="{{ $o->id }}">{{ $o->name }}</option>@endforeach</select></label><label>Confirme sua senha<input name="password" type="password" required autocomplete="current-password"></label><button class="danger">Revogar acesso</button><p class="muted">Preserva a correspondência. Bloqueia as próximas ações e envios ainda não iniciados.</p></form></section></div>
<section class="panel"><h2>Fila durável</h2>@forelse($outbox as $o)<p>{{ $o->status }} · {{ $o->total }}</p>@empty<p>Sem envios na fila.</p>@endforelse</section>
<section class="panel"><h2>Eventos de recebimento</h2><div class="table-wrap"><table><thead><tr><th>Evento</th><th>Estado</th><th>Diagnóstico sanitizado</th></tr></thead><tbody>@forelse($events as $e)<tr><td>{{ $e->type }}</td><td>{{ $e->status }}</td><td>{{ $e->last_error ?? '—' }}</td></tr>@empty<tr><td colspan="3">Nenhum webhook recebido.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><h2>Auditoria sem conteúdo de mensagens</h2><div class="table-wrap"><table><thead><tr><th>Data UTC</th><th>Ação</th><th>Identidade</th></tr></thead><tbody>@foreach($audits as $a)<tr><td>{{ $a->created_at }}</td><td>{{ $a->action }}</td><td>#{{ $a->actor_id }}</td></tr>@endforeach</tbody></table></div></section>
</main>@endsection
