[global]
pid=/tmp/brnmail-fpm.pid
error_log=/proc/self/fd/2
[www]
listen=127.0.0.1:19000
pm=ondemand
pm.max_children=3
pm.process_idle_timeout=10s
pm.max_requests=300
clear_env=yes
catch_workers_output=yes
decorate_workers_output=no
request_terminate_timeout=75s
