expose_php=Off
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2
memory_limit=256M
upload_max_filesize=10M
post_max_size=24M
max_file_uploads=5
max_execution_time=60
date.timezone=UTC
opcache.enable=1
opcache.validate_timestamps=1
opcache.revalidate_freq=0
session.cookie_secure=1
session.cookie_httponly=1
